import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import '../models/monthly_report.dart';
import '../utils/app_utils.dart';

class PdfGenerator {
  static Future<File> generateReport(
      MonthlyReport report, String currency) async {
    final pdfCurrency = currency == '₹' ? 'Rs. ' : currency;
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          // ── Header ────────────────────────────────────
          pw.Container(
            padding: const pw.EdgeInsets.all(20),
            decoration: pw.BoxDecoration(
              color: PdfColors.blueGrey900,
              borderRadius: pw.BorderRadius.circular(12),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'Finora',
                  style: pw.TextStyle(
                    fontSize: 28,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.white,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Monthly Report — ${AppDateUtils.formatMonthYear(report.month, report.year)}',
                  style: pw.TextStyle(
                    fontSize: 14,
                    color: PdfColors.white,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Generated: ${AppDateUtils.formatDate(report.generatedAt)}',
                  style: pw.TextStyle(
                    fontSize: 11,
                    color: PdfColors.grey300,
                  ),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 24),

          // ── Summary ────────────────────────────────────
          pw.Text(
            'Summary',
            style: pw.TextStyle(
              fontSize: 18,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 12),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey300),
            children: [
              _tableRow('Total Income',
                  CurrencyFormatter.format(report.totalIncome, pdfCurrency),
                  isHeader: true),
              _tableRow('Total Expense',
                  CurrencyFormatter.format(report.totalExpense, pdfCurrency)),
              _tableRow(
                  'Net Savings',
                  CurrencyFormatter.format(
                      report.savings.clamp(0, double.infinity), pdfCurrency),
                  isHeader: true),
            ],
          ),
          pw.SizedBox(height: 24),

          // ── Expense Breakdown ──────────────────────────
          if (report.expenseBreakdown.isNotEmpty) ...[
            pw.Text(
              'Expense Breakdown',
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.SizedBox(height: 12),
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey300),
              children: [
                _tableRow('Category', 'Amount', isHeader: true),
                ...report.expenseBreakdown.entries.map((e) =>
                    _tableRow(e.key, CurrencyFormatter.format(e.value, pdfCurrency))),
              ],
            ),
            pw.SizedBox(height: 24),
          ],

          // ── Income Breakdown ───────────────────────────
          if (report.incomeBreakdown.isNotEmpty) ...[
            pw.Text(
              'Income Breakdown',
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.SizedBox(height: 12),
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey300),
              children: [
                _tableRow('Source', 'Amount', isHeader: true),
                ...report.incomeBreakdown.entries.map((e) =>
                    _tableRow(e.key, CurrencyFormatter.format(e.value, pdfCurrency))),
              ],
            ),
          ],

          pw.SizedBox(height: 40),
          pw.Divider(),
          pw.Text(
            'Generated by Finora — Your offline personal finance tracker',
            style: pw.TextStyle(fontSize: 10, color: PdfColors.grey500),
          ),
        ],
      ),
    );

    final dir = await getTemporaryDirectory();
    final filename =
        'finora_${AppDateUtils.fullMonthName(report.month).toLowerCase()}_${report.year}.pdf';
    final file = File('${dir.path}/$filename');
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  static pw.TableRow _tableRow(String col1, String col2,
      {bool isHeader = false}) {
    return pw.TableRow(
      decoration: isHeader
          ? const pw.BoxDecoration(color: PdfColors.blueGrey100)
          : null,
      children: [
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(
            col1,
            style: pw.TextStyle(
              fontWeight: isHeader ? pw.FontWeight.bold : pw.FontWeight.normal,
              fontSize: 12,
            ),
          ),
        ),
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(
            col2,
            style: pw.TextStyle(
              fontWeight: isHeader ? pw.FontWeight.bold : pw.FontWeight.normal,
              fontSize: 12,
            ),
            textAlign: pw.TextAlign.right,
          ),
        ),
      ],
    );
  }
}
